### ISSUE TITLE
Within Apple Messages trackpad touch click often only works after second click?!

### ISSUE THREAD

**Issue by pictosun** [rxhanson/Multitouch-Community#139]
Hi,

just found out, that Multitouch is the problem when touch click or click within messages app.

It often needs to separate clicks/touches (with a short brake between) to select the chat I want to. After closing Multitouch everything is working without any issues.

When I delete my only configured gesture within trackpad (4 finger click to screenshot) it also works without any issues.

So it has something to do with the 4 finger 'click' command that the touchclick is not working as it should.

Quite confusing, isn't it?

I'm on 1.27.10.

**Comment by rxhanson** [comment]
Thanks for letting me know. I'll see if I can reproduce this and figure it out.

**Comment by pictosun** [comment]
Looks like this issue does not appear anymore. Will close it.

**Comment by rxhanson** [comment]
@pcjmfranken thanks for the details. Tap-to-click is inherently difficult to manage as a 3rd party, since macOS does not provide any way to up front distinguish a tap-to-click generated click from an intentional actual click. I've spent a significant amount of a time trying to work around this, and don't have a silver bullet for it yet, provided the way that Multitouch works.
